Repository DS-VitaDigging/front-end, pull requests merged in 2025-08, with the labels that each got.

#18 fix: axiosInstance 수정 및 font 크기 설정 추가
  vita-digging/src/apis/axiosInstance.js
  vita-digging/src/styles/reset.js
Labels: bug, style

#27 [fix] 로그인 및 회원가입 api 연동
  vita-digging/src/apis/auth.js
  vita-digging/src/pages/Category/SupplementList.jsx
  vita-digging/src/pages/Login/Login.jsx
  vita-digging/src/pages/Mypage/Mypage.jsx
  vita-digging/src/pages/Mypage/components/NicknamePopup.jsx
  vita-digging/src/pages/Mypage/components/PasswordPopup.jsx
  vita-digging/src/pages/Signup/Signup.jsx
  vita-digging/src/router.js
Labels: bug, 보경

#37 feat: category api 연동
  vita-digging/public/images/icon_liver.svg
  vita-digging/src/apis/Home/home.js
  vita-digging/src/pages/Category/CategoryCard.jsx
  vita-digging/src/pages/Category/CategorySelect.jsx
  vita-digging/src/pages/Category/CategorySelect.style.js
  vita-digging/src/pages/Category/SupplementDetail.jsx
  vita-digging/src/pages/Category/SupplementDetail.style.js
  vita-digging/src/pages/Category/SupplementList.jsx
  vita-digging/src/pages/Category/SupplementList.style.js
  vita-digging/src/pages/Home/Home.jsx
  vita-digging/src/pages/Mypage/BeforeLogin.jsx
  vita-digging/src/pages/Mypage/Mypage.jsx
  vita-digging/src/pages/Mypage/Mypage.style.js
  vita-digging/src/router.js
Labels: feature, 보경

#40 fix: 회원가입 api 연동 에러 해결
  vita-digging/src/pages/Mypage/Mypage.jsx
  vita-digging/src/pages/Signup/Signup.jsx
Labels: bug, 소이

#42 chore: 회원가입 age, gender 값 문제 + 설문 페이지 스타일 수정
  vita-digging/src/pages/Signup/Signup.jsx
  vita-digging/src/pages/Survey/Results/resultDetailModal.jsx
  vita-digging/src/pages/Survey/Results/resultPage.style.js
Labels: chore, 소이
